version: '3.8'

services:
  ansible-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: ansible-master
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - ansible-net
    tty: true
    volumes:
      - master_ansible:/etc/ansible
      - master_ssh:/root/.ssh
      - master_ansible_root:/root/ansible   # <-- added

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node1
    networks:
      - ansible-net
    volumes:
      - node1_ssh:/root/.ssh
      - node1_sshd:/etc/ssh
      - node1_logs:/var/log

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node2
    networks:
      - ansible-net
    volumes:
      - node2_ssh:/root/.ssh
      - node2_sshd:/etc/ssh
      - node2_logs:/var/log

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node3
    networks:
      - ansible-net
    volumes:
      - node3_ssh:/root/.ssh
      - node3_sshd:/etc/ssh
      - node3_logs:/var/log

networks:
  ansible-net:
    driver: bridge

volumes:
  master_ansible:
  master_ssh:
  master_ansible_root:   # <-- added volume

  node1_ssh:
  node1_sshd:
  node1_logs:

  node2_ssh:
  node2_sshd:
  node2_logs:

  node3_ssh:
  node3_sshd:
  node3_logs:
